TestArea_MapScripts::
	.byte 0


TestArea_Sign1::
# 6 "data/maps/TestArea/scripts.pory"
	lockall
# 7 "data/maps/TestArea/scripts.pory"
	msgbox TestArea_Text_Sign1, MSGBOX_SIGN
# 8 "data/maps/TestArea/scripts.pory"
	releaseall
	end


TestArea_Sign2::
# 13 "data/maps/TestArea/scripts.pory"
	lockall
# 14 "data/maps/TestArea/scripts.pory"
	msgbox TestArea_Text_Sign2, MSGBOX_SIGN
# 15 "data/maps/TestArea/scripts.pory"
	releaseall
	end


TestArea_Sign3::
# 20 "data/maps/TestArea/scripts.pory"
	lockall
# 21 "data/maps/TestArea/scripts.pory"
	msgbox TestArea_Text_Sign3, MSGBOX_SIGN
# 22 "data/maps/TestArea/scripts.pory"
	releaseall
	end


TestArea_Sign4::
# 27 "data/maps/TestArea/scripts.pory"
	lockall
# 28 "data/maps/TestArea/scripts.pory"
	msgbox TestArea_Text_Sign4, MSGBOX_SIGN
# 29 "data/maps/TestArea/scripts.pory"
	releaseall
	end


TestArea_Text_Sign1::
# 33 "data/maps/TestArea/scripts.pory"
	.string "Aspirant Dorms$"

TestArea_Text_Sign2::
# 37 "data/maps/TestArea/scripts.pory"
	.string "Proving Trial Entrance$"

TestArea_Text_Sign3::
# 41 "data/maps/TestArea/scripts.pory"
	.string "Wyrmshire - The birthplace of DRAGONS.$"

TestArea_Text_Sign4::
# 45 "data/maps/TestArea/scripts.pory"
	.string "Nexium Caverns$"
